### ISSUE TITLE
Wiki connection lost/Sync error

### ISSUE THREAD

**Issue by icarothomas94** [expitau/InfiniteCraftWiki#21] opened 2024-05-01 01:00 UTC
I have put the link on my bookmarks, clicked on it while on the game tab, and it gives "Wiki connection lost - use bookmarklet to reconnect" on the game and "Sync error" on the wiki tab. I can see the elements I don't have tagged with red, but I can't find the elements I have that the wiki didn't have yet or my first discoveries. I am using Opera GX and NordVPN, if that's relevant. I have tried with VPN on and off and it didn't work, and I don't know which functions to turn on or off on Opera. Also I have a question, are the discoveries I have that weren't on the wiki yet, including my first discoveries, added into a database, or they show only to me? Thanks in advance!

**Comment by expitau** [comment] 2024-05-01 01:23
There were some issues when we initially deployed it, can you please attempt this again by deleting the bookmarklet and trying again?

Thanks!

**Comment by expitau** [comment] 2024-05-01 01:26
The items that you have created that the wiki doesn't know about (including first discoveries) are not currently taken into account. This is currently just a tool to simplify crafting recipes and show you what you have

**Comment by icarothomas94** [comment] 2024-05-01 01:49
Where did the items that were already in the wiki come from, your save file?

**Comment by icarothomas94** [comment] 2024-05-01 01:53
It still didn't work, I'm using the shortcut on the wiki website

**Comment by expitau** [comment] 2024-05-01 04:02
Looks like you've found a bug! Could you please reproduce, and press ctrl+shift+i on the wiki to open dev tools, navigate to the console tab at the top, and send me a screenshot of the console (and repeat this on neal.fun). Thanks!

**Comment by expitau** [comment] 2024-05-01 04:04
The recipes already present on the wiki are from datasets provided by @Jcw87 and @fan87

**Comment by icarothomas94** [comment] 2024-05-01 04:35
![2024-05-01](https://github.com/expitau/InfiniteCraftWiki/assets/81624489/d3d42c15-a305-4116-9366-190a4fc6ac6f)
![2024-05-01 (1)](https://github.com/expitau/InfiniteCraftWiki/assets/81624489/6d30c4e6-12a8-4ead-a665-b47d928454c5)
![2024-05-01 (2)](https://github.com/expitau/InfiniteCraftWiki/assets/81624489/fef2ecd9-bcbf-4b82-805b-003aef66a1e0)
![2024-05-01 (3)](https://github.com/expitau/InfiniteCraftWiki/assets/81624489/4ed932ba-f36e-45c4-8e09-afe75c0df325)
![2024-05-01 (4)](https://github.com/expitau/InfiniteCraftWiki/assets/81624489/4238eb2a-612d-4777-8b0f-1e8ca77dde95)
![2024-05-01 (5)](https://github.com/expitau/InfiniteCraftWiki/assets/81624489/a3d28301-80c3-4bc6-9825-356aa3e76a4e)
![2024-05-01 (6)](https://github.com/expitau/InfiniteCraftWiki/assets/81624489/b9e8953b-29bc-41aa-9002-698ab6228b5b)
![2024-05-01 (7)](https://github.com/expitau/InfiniteCraftWiki/assets/81624489/811df1a6-de38-4430-8a30-566915f0eb95)
![2024-05-01 (8)](https://github.com/expitau/InfiniteCraftWiki/assets/81624489/b69bfc24-ea94-43f3-a0e5-3d8b3cb29d68)
![2024-05-01 (9)](https://github.com/expitau/InfiniteCraftWiki/assets/81624489/390b0990-624e-41c8-a96c-cbec74b7e26d)

**Comment by expitau** [comment] 2024-05-01 12:05
Hm, my first thought is that it's a caching error. Try a hard refresh (Ctrl + F5), or clearing your browser cache and cookies (History -> clear browsing data -> advanced)

**Comment by expitau** [comment] 2024-05-01 21:52
Hard refresh, or selecting "cached images and files" when clearing history will not erase your infinite craft data

**Comment by icarothomas94** [comment] 2024-05-02 03:00
it erased my infinite craft data

**Comment by expitau** [comment] 2024-05-02 20:22
What? Did you select cached images and files when clearing history? I've just tested both and it didn't clear anything

![image](https://github.com/expitau/InfiniteCraftWiki/assets/84288806/97422a09-dd54-4607-8a70-db4946ce40c9)

![image](https://github.com/expitau/InfiniteCraftWiki/assets/84288806/f1ca3d7e-b598-4e63-8216-f535781e7125)

**Comment by expitau** [comment] 2024-05-02 20:37
Closing as unable to reproduce. Very sorry I was unable to help

**Closed by expitau** 2024-05-02 20:37 UTC
Labels: bug
